### ISSUE TITLE
Feature-Request: Placeholder with default handling

### ISSUE THREAD

**Issue by blaubaer** [caddyserver/caddy#1793]
If there is no/empty for a placeholder use default/fallback value/placeholder.

#### Pattern
```
{foo:-{bar}}
```
#### Expectations
| `foo` | `bar` | Result |
| - | - | - |
| `John` | `Mark` | `John` |
| `John` | _empty_ | `John` |
| _empty_ | `Mark` | `Mark` |
| _empty_ | _empty_  | _empty_  |

### Usage example
```
proxy /api my-api:80 {
    transparent
    websocket
    without /api
    header_upstream X-Forwarded-Path {>X-Forwarded-Path:-{path}}
}
```
> If this caddy is also behind a reverse proxy it also will set the header `X-Forwarded-Path` ... in this case use this header. If not set we expect to be not behind a reverse proxy and directly called ... in this case use `path`.

### Other software which uses this pattern
https://logback.qos.ch/manual/configuration.html#defaultValuesForVariables

**Comment by mholt** [comment]
Will be mostly irrelevant in Caddy 2, which provides this capability through other means.

**Comment by yesiyan01** [comment]
Any updates on this one?

**Comment by francislavoie** [comment]
@yesiyan01 what exactly are you looking for? Could you be more specific?

**Comment by yesiyan01** [comment]
@francislavoie 

I have a reverse proxy handler that overrides authorization header e.g.

```
handler: reverse_proxy
headers:
  request:
    set:
      Authorization:
        - '{http.oauth1}'
transport:
   protocol: http
   tls: {}
upstreams:
   - dial: 'xxx.com:443'

```

where 'http.oauth1' is a custom header value set from a custom module.

I'd like the ability to use 'http.oauth1' in the placeholder but fallback to a static API-KEY when http.oauth1 is not present.
