### ISSUE TITLE
Env var for domain names not supported?

### ISSUE THREAD

**Issue by ckcollab** [caddyserver/caddy#2636]
Hello! First of all, thanks so much for Caddy... it has been a lifesaver :)

## 1. Which version of Caddy are you using (`caddy -version`)?

`Caddy 0.11.5 (unofficial)`

## 2. What are you trying to do?

Pass `{$CADDY_DOMAIN}` to our `Caddyfile` for multiple domains

## 3. What is your Caddyfile?
```text
paste entire Caddyfile here - DO NOT REDACT ANYTHING (except credentials)
```

```
{$CADDY_DOMAIN} {
    gzip
    root /var/www/testing
    proxy / web:8000 {
        transparent
        except /static
    }

    push
}
```

The above fails the following ways with the following inputs:

```
# CADDY_DOMAIN=http://localhost, https://testing.serveo.net
2019/06/03 17:33:52 error inspecting server blocks: parse http://localhost, https://testing.serveo.net: invalid character " " in host name
```

```
# CADDY_DOMAIN=http://localhost,https://testing.serveo.net
2019/06/03 17:41:17 [INFO] Serving http://localhost,https//testing.serveo.net

# (note the domain is wrong, smashed both together)
```

However when I put the text straight in the `Caddyfile`, it works!

```
# This works!
http://localhost,https://testing.serveo.net {
    gzip
    root /var/www/testing
    proxy / web:8000 {
        transparent
        except /static
    }

    push
}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?

From a docker container, defined like so....

```
  caddy:
    image: abiosoft/caddy:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./conf/Caddyfile:/etc/Caddyfile
      - ./testing/static:/var/www/testing/static
      - ./docker_storage/certs/caddy:/etc/caddycerts
    ports:
      - 80:2015
      - 443:443
    depends_on:
      - web
```

## Bonus: What do you use Caddy for? Why did you choose Caddy?

For the easy HTTP/2 and SSL :)
