### ISSUE TITLE
v2: Support CUE language as config file format

### ISSUE THREAD

**Issue by shibumi** [caddyserver/caddy#2907]
## 1. What would you like to have changed?

Right now caddy2 has two config adapters: Caddyfile and JSON.
I have to admit, that I am not a big fan of json, because it's not possible to insert comments and it's difficult to write manual.

JSON is a format that should be used only from one computer to another.

I know that there is caddyfile config support, but the documentation says that the caddyfile support is not complete (there are certain options that will be only configurable via JSON).

So how to resolve this problem?

The answer for this could be the CUE language. CUE is a superset of JSON, can be transformed into JSON, and brings certain other benefits like validation with schemes (could be very useful for config files).

## 2. Why is this feature a useful, necessary, and/or important addition to this project?

CUE would make the configuration a lot easier. People would be able to use all features in the json config adapter and the config file would still be readable + it would be possible to insert comments.

The project would benefit of CUE in other parts as well (validation with schemes and fixed datatypes could be a lot more easier with CUE).

I really recommend this short CUE tutorial:

https://cuelang.org/docs/tutorials/tour/

I can imagine this as third-party config adapter package. CUE is a superset of json, therefore somebody could just parse CUE and pipe all the output into the caddy2 JSON config adapter and this should be fine. (Although the best part is the validation via schemes in CUE etc).

Here is a short example from YAML to CUE with a kubernetes deployment file:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
```
Same in JSON:
```json
{
  "apiVersion": "apps/v1",
  "kind": "Deployment",
  "metadata": {
    "name": "hello-kubernetes"
  },
  "spec": {
    "replicas": 3,
    "selector": {
      "matchLabels": {
        "app": "hello-kubernetes"
      }
    },
    "template": {
      "metadata": {
        "labels": {
          "app": "hello-kubernetes"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "hello-kubernetes",
            "image": "paulbouwer/hello-kubernetes:1.5",
            "ports": [
              {
                "containerPort": 8080
              }
            ]
          }
        ]
      }
    }
  }
}
```

Here is the equivalent in CUE:
```cue
// This is a comment
apiVersion: "apps/v1"
kind:       "Deployment"
metadata name: "hello-kubernetes"
spec: {
  replicas: 3
  selector matchLabels app: "hello-kubernetes"
  template: {
    metadata labels app: "hello-kubernetes"
    spec containers: [{
      name:  "hello-kubernetes"
      image: "paulbouwer/hello-kubernetes:1.5"
      ports: [{
        containerPort: 8080
      }]
    }]
  }
}
```
