### ISSUE TITLE
2.2.0 "unable to create context store: mkdir /etc/caddy: permission denied" when reloading config using docker caddy

### ISSUE THREAD

**Issue by kwypchlo** [caddyserver/caddy#3760]
Hello! I just upgraded from 2.1.1 to 2.2.0 and switched from using caddy-builder to xcaddy in my Dockerfile (below). I used to to `docker exec caddy caddy reload --config /etc/caddy/Caddyfile` to reload `Caddyfile` changes (mounted) but this command now returns `unable to create context store: mkdir /etc/caddy: permission denied`. 

My docker-compose entry:
```
  caddy:
    build:
      context: ./docker/caddy
      dockerfile: Dockerfile
    container_name: caddy
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./docker/data/caddy/data:/data
      - ./docker/data/caddy/config:/config
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      shared:
        ipv4_address: 192.168.0.20
    ports:
      - "80:80"
      - "443:443"
```

My Dockerfile
```
FROM caddy:2.2.0-builder AS caddy-builder

# available dns resolvers: https://github.com/caddy-dns
RUN xcaddy build --with github.com/caddy-dns/route53

FROM caddy:2.2.0

COPY --from=caddy-builder /usr/bin/caddy /usr/bin/caddy
```

I would appreciate any help :) Thanks for the great piece of software!
