### ISSUE TITLE
Promethus Metrics fail with gzip: invalid header

### ISSUE THREAD

**Issue by b3ntly** [caddyserver/caddy#3764]
Experimenting with the metrics directive within a larger project, I'm running into a vague error preventing scraping of the metrics by Prometheus.

### Steps to reproduce

docker-compose.yml
```
version: "3"

services:
  ## some services omitted 

  caddy:
    image: caddy:latest
    network_mode: "host"
    volumes:
      - caddy-data:/data 
      - caddy-config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile 

  prometheus:
    image: prom/prometheus
    network_mode: "host"
    volumes:
      - prometheus-storage:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  prometheus-storage:
  caddy-data:
  caddy-config:
```

Caddyfile

```
localhost {
  metrics /metrics

  reverse_proxy {
      to localhost:4200
  } 
}
```

prometheus.yml
```
global:
    scrape_interval: 15s
    scrape_timeout: 10s
    evaluation_interval: 15s
    
alerting:
  alertmanagers:
  - scheme: http
    timeout: 10s
    api_version: v1
    static_configs:
    - targets: []

scrape_configs:
- job_name: caddy
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https
  tls_config:
    insecure_skip_verify: true  
  static_configs:
  - targets:
    - localhost
```

I'm running caddy within a docker container which shares the host network, using it as a reverse proxy on localhost and to serve a self-signed certificate during development. This may be a prometheus issue, and it may pertain to localhost, but I wanted to post it here incase there was an obvious cause or as a breadcrumb to anyone else experiencing this issue.

Showing the Prometheus UI error description.

![Screenshot from 2020-09-29 17-01-30](https://user-images.githubusercontent.com/7690509/94628823-e4eb7f00-0275-11eb-8e13-1ddbbfdab99c.png)

Showing the result of clicking ```https://localhost/metrics``` from the image above. Notably it seems to resolve localhost to something else (ben being my Ubuntu 18.04 username).

![Screenshot from 2020-09-29 17-01-52](https://user-images.githubusercontent.com/7690509/94628828-e87f0600-0275-11eb-9c4a-114f2a541c7c.png)

Finally here are the headers when manually going to https://localhost/metrics , which returns just fine.

![Screenshot from 2020-09-29 17-02-54](https://user-images.githubusercontent.com/7690509/94628832-ea48c980-0275-11eb-83f7-da11f9bf77d5.png)

Any thoughts? Let me know if more information will be helpful.
