### ISSUE TITLE
Re-compressing content with a reverse proxy

### ISSUE THREAD

**Issue by merlinnot** [caddyserver/caddy#3863]
Hi! I have a fairly unusual Caddy setup and I'm uncertain about the specific behavior regarding compression. I'd be willing to contribute to the documentation to clarify it, but I can't do that without full understanding, hence I'm asking here first.

My setup in short:
- An origin server, static files only (hereinafter **origin**).
- AMP Packager for file transformation and signing using Signed HTTP Exchanges (hereinafter **packager**).
- A front reverse proxy, which directs traffic between the packager and the static server (hereinafter **proxy**).

The origin listens on a Unix socket and a network port at the same time. Unix socket is used by the proxy, while TCP is used by the packager, which doesn't support unix sockets yet. Data from the packager must be compressed dynamically, as the signature is a part of the response body and it changes with every single response. However, origin has access to pre-compressed static files, so I'd like it to serve those straight away. What I'm wondering is if the proxy will uncompress them and compress again?

Here's my current configuration:

```yaml
handler_reverse_proxy_origin: &handler_reverse_proxy_origin
  handler: reverse_proxy
  transport:
    compression: false
    protocol: http
    versions:
      - '2'
  upstreams:
    - dial: 'unix//var/run/origin.sock'

handler_reverse_proxy_amppkg: &handler_reverse_proxy_amppkg
  handler: reverse_proxy
  transport:
    compression: false
    keep_alive:
      enabled: false
    protocol: http
    versions:
      - '2'
  upstreams:
    - dial: '127.0.0.1:8081'

handler_headers_security: &handler_headers_security
  handler: headers
  response:
    set:
      Content-Security-Policy:
        # `child-src` should be removed once `worker-src` is supported across
        # all browsers.
        # `script-src: unsafe-inline` should be removed once `script-src-elem`
        # is supported across all browsers or the inline scripts are secured
        # using hashes or nonces.
        #
        # Safari does not respect the CSP specification in regards to schemes,
        # therefore all URLs must be prefixed with https://.
        - "\
          default-src 'none';\
          base-uri 'none';\
          child-src blob:;\
          connect-src 'self' https://*.ampproject.net
          https://cdn.ampproject.org;\
          font-src 'self' https://fonts.gstatic.com;\
          form-action 'self';\
          frame-ancestors 'self';\
          frame-src 'self' https://*.ampproject.net https://cdn.ampproject.org;\
          img-src 'self' data: https://maps.gstatic.com https://*.googleapis.com
          https://*.ggpht.com;\
          manifest-src 'self';\
          script-src 'self' 'unsafe-inline' https://cdn.ampproject.org
          maps.googleapis.com;\
          script-src-elem 'unsafe-inline' https://cdn.ampproject.org
          https://maps.googleapis.com https://polyfill.io;\
          style-src 'unsafe-inline' https://fonts.googleapis.com;\
          worker-src blob:;\
          sandbox allow-popups allow-same-origin allow-scripts
          allow-top-navigation-by-user-activation;\
          upgrade-insecure-requests; block-all-mixed-content;\
          "
      Referrer-Policy:
        - same-origin
      Strict-Transport-Security:
        - max-age=63072000; includeSubDomains; preload
      X-Content-Type-Options:
        - nosniff
      X-Frame-Options:
        - SAMEORIGIN
      X-XSS-Protection:
        - 1; mode=block

handler_headers_override: &handler_headers_override
  handler: headers
  response:
    deferred: true
    delete:
      - 'Server'
    set:
      Vary:
        - 'Accept, Accept-Encoding, AMP-Cache-Transform'

handler_encode_dynamic_compress: &handler_encode_dynamic_compress
  handler: encode
  encodings:
    gzip:
      level: 3
    zstd: {}

handler_file_server_var_www: &handler_file_server_var_www
  canonical_uris: false
  handler: file_server
  index_names:
    - index.html
  root: /var/www

caddy:
  admin:
    config:
      persist: false
    disabled: true
  apps:
    http:
      servers:
        # Origin serves static files.
        origin:
          allow_h2c: true
          automatic_https:
            disable: true
          listen:
            - unix//var/run/origin.sock
            - '127.0.0.1:8082'
          routes:
            - handle:
                - handler: headers
                  response:
                    set:
                      Cache-Control:
                        - immutable, max-age=31536000, public
                - <<: *handler_headers_security
                - <<: *handler_file_server_var_www
              match:
                - path:
                    - '/assets/*'
              terminal: true
            # Redirect trailing slashes, `*/index` and `*/index.html` paths to
            # clean URLs.
            - handle:
                - <<: *handler_headers_security
                - handler: static_response
                  headers:
                    location:
                      - '{http.regexp.path.clean_uri}'
                  status_code: 301
              match:
                - path_regexp:
                    name: path
                    pattern: '^(?P<clean_uri>\/.*?)(?:\/|\/?index|\/?index\.html)$'
              terminal: true
            # Redirect legacy links.
            - handle:
                - <<: *handler_headers_security
                - handler: static_response
                  headers:
                    location:
                      - '/terms-and-conditions'
                  status_code: 301
              match:
                - path:
                    - /terms
              terminal: true
            # Serve all static files.
            - handle:
                - handler: headers
                  response:
                    set:
                      Cache-Control:
                        - max-age=43200, public, stale-while-revalidate=86400,
                          stale-if-error=604800
                - <<: *handler_headers_security
                - <<: *handler_file_server_var_www
              terminal: true
        # Proxy directs traffic between the file server and AMP Packager.
        proxy:
          allow_h2c: true
          automatic_https:
            disable: true
          listen:
            - ':8080'
          routes:
            # Compress all responses for formats not already compressed.
            # Statically compressed files are available in both gzip and Brotli
            # formats, but Caddy does not support static compression yet.
            - handle:
                - <<: *handler_encode_dynamic_compress
              match:
                - not:
                    - path:
                        - '*.jpeg'
                        - '*.jpg'
                        - '*.png'
                        - '*.webp'
                        - '*.woff2'
            - handle:
                - <<: *handler_encode_dynamic_compress
                - <<: *handler_headers_override
                - handler: rewrite
                  uri: "/priv/doc?\
                    fetch=http://127.0.0.1:8082{http.request.orig_uri.path}&\
                    sign=https://ridedott.com{http.request.orig_uri.path}"
                - <<: *handler_reverse_proxy_amppkg
              match:
                - header:
                    AMP-Cache-Transform: []
              terminal: true
            - handle:
                - <<: *handler_headers_override
                - <<: *handler_reverse_proxy_amppkg
              match:
                - path:
                    - '/amppkg/*'
              terminal: true
            - handle:
                - <<: *handler_headers_override
                - <<: *handler_reverse_proxy_origin
              terminal: true
  logging:
    logs:
      default:
        encoder:
          format: console
        level: INFO
        writer:
          output: stdout
    sink:
      writer:
        output: stdout
```
