### ISSUE TITLE
cannot reverse proxy in front of grpc + grpc-web multiplexer

### ISSUE THREAD

**Issue by tiero** [caddyserver/caddy#3997]
I have a go server that does multiplexing of grpc and grpc.web based on content-type, this means I accept both http/1.1 and http2 with TLS. Unfortunately it seems impossible to have all version in the `http` transport directive of `reverse_proxy`, either I support plain text grpc-web or http2 binary grpc.

The go server expect the TLS cert and key (wich I generated with caddy)

## This is my Caddyfile

```
https://api.mydomain.com

log {
    level INFO
}

reverse_proxy {
    to h2c://api:8000
    transport http {
        versions h2c 2
    }
}
```

## This is what it logs caddy when calling /Service/Method  with a grpc client

```sh

{
  "level": "error",
  "ts": 1611876892.228595,
  "logger": "http.log.error.log0",
  "msg": "write tcp 172.30.0.3:53400->172.30.0.2:8000: write: broken pipe",
  "request": {
    "remote_addr": "5.90.3.181:36177",
    "proto": "HTTP/2.0",
    "method": "POST",
    "host": "api.mydomain.com",
    "uri": "/Service/Method",
    "headers": {
      "User-Agent": [
        "grpc-node/1.24.2 grpc-c/8.0.0 (linux; chttp2; ganges)"
      ],
      "Grpc-Accept-Encoding": [
        "identity,deflate,gzip"
      ],
      "Accept-Encoding": [
        "identity,gzip"
      ],
      "Te": [
        "trailers"
      ],
      "Content-Type": [
        "application/grpc"
      ]
    },
    "tls": {
      "resumed": false,
      "version": 771,
      "cipher_suite": 49196,
      "proto": "h2",
      "proto_mutual": true,
      "server_name": "api.mydomain.com"
    }
  },
  "duration": 0.005654583,
  "status": 502,
  "err_id": "n9kacgca2",
  "err_trace": "reverseproxy.statusError (reverseproxy.go:783)"
}
```

```sh
{
  "level": "error",
  "ts": 1611876892.2293694,
  "logger": "http.log.access.log0",
  "msg": "handled request",
  "request": {
    "remote_addr": "5.90.3.181:36177",
    "proto": "HTTP/2.0",
    "method": "POST",
    "host": "api.mydomain.com",
    "uri": "/Service/Method",
    "headers": {
      "Content-Type": [
        "application/grpc"
      ],
      "User-Agent": [
        "grpc-node/1.24.2 grpc-c/8.0.0 (linux; chttp2; ganges)"
      ],
      "Grpc-Accept-Encoding": [
        "identity,deflate,gzip"
      ],
      "Accept-Encoding": [
        "identity,gzip"
      ],
      "Te": [
        "trailers"
      ]
    },
    "tls": {
      "resumed": false,
      "version": 771,
      "cipher_suite": 49196,
      "proto": "h2",
      "proto_mutual": true,
      "server_name": "api.mydomain.com"
    }
  },
  "common_log": "5.90.3.181 - - [28/Jan/2021:23:34:52 +0000] \"POST /Service/Method HTTP/2.0\" 502 0",
  "duration": 0.005654583,
  "size": 0,
  "status": 502,
  "resp_headers": {
    "Server": [
      "Caddy"
    ]
  }
}
```

## My docker compose

```yaml
version: "3.7"

services:
  api:
    container_name: "my_container"
    image: my_api:latest
    restart: unless-stopped
    environment:
      - SSL_CERT=./cert.pem
      - SSL_KEY=./key.pem
    ports:
      - "8000:8000"
    volumes:
      - path/to/cert.crt:/cert.pem
      - path/to/key.key:/key.pem
  caddy:
    container_name: "caddy"
    image: caddy:latest
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $HOME/Caddyfile:/etc/caddy/Caddyfile
      - $HOME/caddy-data:/data

```
