### ISSUE TITLE
Explanation of the docker-compose file for Caddy

### ISSUE THREAD

**Issue by Muddz** [caddyserver/caddy#4094]
I would like an explanation of the different parts of the docker-compose file for caddy from the official [docker hub repo](https://hub.docker.com/_/caddy?tab=description):

```
version: '3.8'

services:
 caddy:
    image: caddy:latest
    container_name: caddy
    ports:
    - 80:80
    - 443:443
    volumes:
    - /home/ubuntu/docker-volumes/caddy/Caddyfile/:/etc/caddy/Caddyfile
    - /home/ubuntu/docker-volumes/caddy/site:/srv
    - caddy_data:/data
    - caddy_config:/config
    networks:
    - main
    restart: unless-stopped

networks:
 main:
  external: true

volumes:
  caddy_data:
  caddy_config:
```

1. Is there a default caddyfile at `/etc/caddy/Caddyfile` which can automatically be mounted to my host-path at `myhost/docker-volumes/caddy/Caddyfile`? or do I have to manually write on before launching the docker-compose file?

2. What is the path `/srv` used for?

3. What is the external volumes `caddy_data:` and `caddy_config:`?

4. How do I specify my domains with TLS/HTTPS config in the docker-compose file?
