### ISSUE TITLE
Bug: index out of range [-1] when starting caddy

### ISSUE THREAD

**Issue by psrcek** [caddyserver/caddy#4101]
Upon starting caddy the following is printed in a loop (I'm assuming because my container automatically restarts)
This only happens one one of my 2 servers, with the same config, which is very weird.

```
{"level":"info","ts":1617283700.1680074,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/caddyserver/caddy/v2/caddyconfig/httpcaddyfile.consolidateAutomationPolicies(0xc00052e800, 0x3, 0x40, 0x0, 0x0, 0xc0006e0de0)
	github.com/caddyserver/caddy/v2@v2.4.0-beta.1/caddyconfig/httpcaddyfile/tlsapp.go:498 +0xc4a
github.com/caddyserver/caddy/v2/caddyconfig/httpcaddyfile.ServerType.buildTLSApp(0xc0001f25a0, 0x5, 0x5, 0xc0006bb800, 0x0, 0x0, 0x0, 0xc000b7af60, 0x0, 0x0, ...)
	github.com/caddyserver/caddy/v2@v2.4.0-beta.1/caddyconfig/httpcaddyfile/tlsapp.go:356 +0xed8
github.com/caddyserver/caddy/v2/caddyconfig/httpcaddyfile.ServerType.Setup(0xc0007a1000, 0x43, 0x80, 0xc0006bb800, 0xc0001e5080, 0x5, 0x8, 0x0, 0xc0006bb9b0, 0x0)
	github.com/caddyserver/caddy/v2@v2.4.0-beta.1/caddyconfig/httpcaddyfile/httptype.go:218 +0x1095
github.com/caddyserver/caddy/v2/caddyconfig/caddyfile.Adapter.Adapt(0x1a26a40, 0x2414708, 0xc000374840, 0xb5, 0x2b5, 0xc0006bb800, 0xc0003ba360, 0x62000000016fda40, 0xc000bdf598, 0x626ade64124565c6, ...)
	github.com/caddyserver/caddy/v2@v2.4.0-beta.1/caddyconfig/caddyfile/adapter.go:50 +0x162
github.com/caddyserver/caddy/v2/cmd.loadConfig(0x7ffd96f44ec0, 0x14, 0x7ffd96f44edf, 0x9, 0xc000194330, 0x403e33, 0xc000bdfac0, 0x756ea1a0777002, 0x3026626bc76bb325, 0x40e3b8, ...)
	github.com/caddyserver/caddy/v2@v2.4.0-beta.1/cmd/main.go:177 +0x644
github.com/caddyserver/caddy/v2/cmd.cmdRun(0xc0001843c0, 0x0, 0x0, 0x0)
	github.com/caddyserver/caddy/v2@v2.4.0-beta.1/cmd/commandfuncs.go:206 +0x805
github.com/caddyserver/caddy/v2/cmd.Main()
	github.com/caddyserver/caddy/v2@v2.4.0-beta.1/cmd/main.go:85 +0x248
main.main()
	caddy/main.go:12 +0x25
```

Dockerfile:
```
FROM caddy:2-builder-alpine AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare

FROM caddy:2-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

docker-compose.yml:
```
version: '3.7'

services:
  caddy:
    image: caddy:2-dns-cloudflare
    build: .
    container_name: caddy
    restart: always
    environment:
      XDG_DATA_HOME: /shared/data
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /path/to/my/config/caddy:/etc/caddy
      - config:/config
      - shared:/shared
```
