### ISSUE TITLE
Basic Auth causes Caddy to use an extraordinary amount of CPU while viewing the NetData Dashboard

### ISSUE THREAD

**Issue by douglasparker** [caddyserver/caddy#4267]
### Operating System
**OS:** Ubuntu 20.04.2 LTS
**CPU:** 8 Cores
**RAM:** 8 GB RAM
**Swap:** 4 GB Swap
**Disk:** 160 GB NVMe SSD

### Applications
**Caddy:** v2.0.0-rc.3 h1:z2H/QnaRscip6aZJxwTbghu3zhC88Vo8l/K57WUce4Q=
**NetData:** v1.31.0

### Configuration

**Caddy** - Caddyfile
```
https://monitor.douglas-parker.com {

    basicauth * {
        douglasparker <redacted>
    }
        reverse_proxy 127.0.0.1:19999
}
```

**NetData** - netdata.conf
```
[global]
    debug log = none
    error log = none
    access log = none

    memory mode = dbengine
    dbengine multihost disk space = 64
    page cache size = 32
    update every = 1

[web]
    enable gzip compression = no
```

## Summary
Caddy will use extreme amounts of CPU usage when you enable basic auth and have many requests being made. In my case, CPU usage spikes to 75%-100% while I am viewing the NetData Dashboard. I can only assume that this has to do with the overhead of the bcrypt algorithm plus many metrics being updated in the dashboard in real time.

I had assumed that this was resolved with commit cc81de9dc95a8b045087c5c84bc7718814083e10 which resolved issue #3462, but it appears that this is still a major issue with basic auth.

## Workarounds
I can work around this issue by lowering the frequency that metrics are collected. For example, updating the dashboard every 5 seconds instead of every 1 second. However, there is still a massive CPU spike when the data is finally sent.

Disabling basic auth completely resolves this issue, but isn't a viable solution for many.

Switching to another web server such as nginx also resolves this issue.

## Screenshots
**Basic Auth Disabled**
![basic-auth-disabled](https://user-images.githubusercontent.com/18235822/128075825-e321e3fe-9bb1-4045-bd20-0952878efa4f.png)

**Basic Auth Enabled**
![basic-auth-enabled](https://user-images.githubusercontent.com/18235822/128075868-9f094e47-3f75-4003-a925-0ca444d0ea10.png)

**Comment by francislavoie** [comment]
> Caddy: v2.0.0-rc.3 h1:z2H/QnaRscip6aZJxwTbghu3zhC88Vo8l/K57WUce4Q=

That's a _very_ old version. Please use v2.4.3.

**Comment by douglasparker** [comment]
@francislavoie I am using the official Caddy docker image. Docker Hub says that `caddy:latest` was last updated **4 days ago**.

**docker-compose.yml**
```
services:
  caddy:
    image: caddy/caddy:latest
    container_name: caddy
    network_mode: host
    volumes:
      - /opt/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - /opt/caddy/data:/data
      - /opt/caddy/config:/config
      - /var/www:/var/www
    restart: unless-stopped
    ```
