### ISSUE TITLE
Bug: In reverse proxy {host} is the same as upstream host

### ISSUE THREAD

**Issue by thommeo** [caddyserver/caddy#4430]
## Problem

In reverse proxy block, there is no way to refer to the `{host}` from the original request.

## Use case:

```
:80 {
  reverse_proxy https://example.com {
    header_up Host {upstream_hostport}
    header_down Set-Cookie "Domain=example.com" "Domain={host}"
  }
}
```

### Config

```
:80 {
  reverse_proxy https://example.com {
    header_up Host {upstream_hostport}
    header_down X-Orig-Host {host}
  }
}
```

### Result

```
$ curl -I http://localhost
HTTP/1.1 200 OK
...
X-Orig-Host: example.com
```

### Expected

```
X-Orig-Host: localhost
```

**Comment by francislavoie** [comment]
Sorry about the locking of the issue, fat-fingered the button 🤦‍♂️

Hmmm. What are you trying to do exactly?

Instead of using the `header_down` subdirectory of `reverse_proxy`, use the `header` directive.

Essentially what's happening is the request actually gets modified by the `reverse_proxy` handler so that it can copy the request to the upstream, but after it's done it reverts any header modifications it's done to make the upstream request. So placeholders in `header_down` which read from the request actually see the modified values since it runs before `reverse_proxy` is done. Using the `header` directive instead will make sure the original request details will be read from.

**Comment by artdnlv** [comment]
> Hmmm. What are you trying to do exactly? I'm not sure what exactly you're trying to achieve with that config.

I am trying to replace the `Domain` in the `Set-Cookie` header with the one from the current HTTP request.

> Instead of using the `header_down` subdirectory of `reverse_proxy`, use the `header` directive.

I'm probably missing something, so I'd be happy if you point me the correct way of using it. Here is what I tried:

docker-compose.yml

```
version: '3'

services:
  proxy:
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile-proxy:/etc/caddy/Caddyfile
    ports:
      - 81:80
    command: caddy run --config /etc/caddy/Caddyfile --watch

  mock:
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile-mock:/etc/caddy/Caddyfile
    ports:
      - 82:80
    command: caddy run --config /etc/caddy/Caddyfile --watch
```

Caddyfile-proxy:

```
:80 {
  reverse_proxy mock:80 {
    header_up Host {upstream_hostport}
    header_down Set-Cookie "Domain=[^;]+" "Domain={host}"
  }

  header X-Proxy-Host {host}
  header Set-Cookie "Domain=[^;]+" "Domain={host}"
}
```

Caddyfile-mock

```
:80 {
  header Set-Cookie "value=true; Domain=some-domain.com;"
}
```

Validate

``` bash
$ curl -sI -H 'Host: expected.com' http://localhost:81/ | grep -E "(Set-Cookie|X-Proxy-Host)"
Set-Cookie: value=true; Domain=mock;
X-Proxy-Host: expected.com
```

Expected header:

```
Set-Cookie: value=true; Domain=expected.com;
X-Proxy-Host: expected.com
```

**Comment by thommeo** [comment]
> Hmmm. What are you trying to do exactly? I'm not sure what exactly you're trying to achieve with that config.

I am trying to replace the `Domain` in the `Set-Cookie` header with the one from the current HTTP request.

> Instead of using the `header_down` subdirectory of `reverse_proxy`, use the `header` directive.

I'm probably missing something, so I'd be happy if you point me the correct way of using it. Here is what I tried:

docker-compose.yml

```
version: '3'

services:
  proxy:
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile-proxy:/etc/caddy/Caddyfile
    ports:
      - 81:80
    command: caddy run --config /etc/caddy/Caddyfile --watch

  mock:
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile-mock:/etc/caddy/Caddyfile
    ports:
      - 82:80
    command: caddy run --config /etc/caddy/Caddyfile --watch
```

Caddyfile-proxy:

```
:80 {
  reverse_proxy mock:80 {
    header_up Host {upstream_hostport}
    header_down Set-Cookie "Domain=[^;]+" "Domain={host}"
  }

  header X-Proxy-Host {host}
  header Set-Cookie "Domain=[^;]+" "Domain={host}"
}
```

Caddyfile-mock

```
:80 {
  header Set-Cookie "value=true; Domain=some-domain.com;"
}
```

Validate

``` bash
$ curl -sI -H 'Host: expected.com' http://localhost:81/ | grep -E "(Set-Cookie|X-Proxy-Host)"
Set-Cookie: value=true; Domain=mock;
X-Proxy-Host: expected.com
```

Expected header:

```
Set-Cookie: value=true; Domain=expected.com;
X-Proxy-Host: expected.com
```

Thanks!
