### ISSUE TITLE
Regression: Reverse proxying a specific service works in 2.5.2 but not 2.6.1.

### ISSUE THREAD

**Issue by GOATS2K** [caddyserver/caddy#5085]
I've just run into some issues with reverse proxying the qBittorrent web UI with Caddy 2.6.1.
The `torrent-client` snippet is the one that matters here.

The root route works, but `/qbt` fails with a blank error page with the log:

```
{"level":"error","ts":1664213703.8793285,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"context canceled"}
```

This works fine in version 2.5.2.

## Dockerfile
```Dockerfile
FROM caddy:2.5.2-builder AS builder
RUN xcaddy build \
	--with github.com/caddy-dns/cloudflare
FROM caddy:2.5.2
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

I just swapped out the version numbers for the upgrade.

## Compose

```yml
version: "3.9"

networks:
  default:
    name: container-net
    external: true

services:
  caddy:
    container_name: caddy
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /home/goats/.containers/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/goats/.containers/caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:
```

## Caddyfile

```
(tls-config) {
        tls {
                dns cloudflare sekrittoken123
        }
}

# Display name - service to proxy
(d1-service-proxy) {
        @{args.0} {
                host {args.0}.domain1.tld
        }

         handle @{args.0} {
                reverse_proxy {args.1}
        }
}
(torrent-client) {
        @{args.0}-flood {
                host {args.0}.domain2.tld
        }

        @{args.0}-qbit {
                host {args.0}.domain2.tld
                path /qbt*
        }

        handle @{args.0}-flood {
                reverse_proxy http://flood-{args.0}:3001
        }

        handle @{args.0}-qbit {
                uri strip_prefix /qbt
                redir /qbt /qbt/
                reverse_proxy http://qbt-{args.0}:8080
        }
}

*.domain1.tld {
        import tls-config
        import d1-service-proxy syncthing http://syncthing:8384
}

*.domain2.tld {
        import tls-config
        log {
                level info
                output stdout
                format console
        }

        import torrent-client misc
}
```
