### ISSUE TITLE
docker wrapped https server taking too long time to response http.handlers.reverse_proxy aborting with incomplete response error 

### ISSUE THREAD

**Issue by kamane** [caddyserver/caddy#5218]
Environnement : Docker 19.03.12 on Ubuntu 20.04 
Error : https server taking too long time to response, with error  aborting with incomplete response error 

**Fix: moving to a debian server fix the issue** 
Rootcause : Not found 

Caddyfile

```
{
debug
}
www.yourwebsite.com , yourwebsite.com {
        root * /var/www/html
        php_fastcgi wordpress:9000
        encode zstd gzip
        file_server
}
```

docker-compose.yml

```
version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:5.8.1-php7.4-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network
 
  caddy:
    image: caddy:alpine
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      -  wordpress:/var/www/html
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - app-network

volumes:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge
```
