### ISSUE TITLE
possible bug with 1xx status code handling

### ISSUE THREAD

**Issue by helmut72** [caddyserver/caddy#5280]
Reference:
https://caddy.community/t/caddy-2-6-x-stop-webdav-client-to-finish-uploading/17975

"It’s about client receiving 100 status twice. Once from stdlib, another from reverse proxy."

**Comment by dunglas** [comment]
If someone manages to add a failing test, I can take a look!

**Comment by helmut72** [comment]
Where should a failing test added?

**Comment by mholt** [comment]
@helmut72 Do you have a really simple reproducer? Ideally just a couple of lines of Caddyfile. That'd be a good start.

**Comment by helmut72** [comment]
Caddyfile(s) of my complete configuration for this specific site, which serves a webdav service:

```
{
    servers :443
    servers :8448
    #debug
    admin :2019
}
import snippets/*.conf
import sites/*.conf
```

snippets/wildcard.conf

```
(wildcard) {
    tls /letsencrypt/certificates/_.example.com.crt /letsencrypt/certificates/_.example.com.key
}
```

snippets/client_headers.conf

```
(client_headers) {
    header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
    header -Server
}
```

snippets/backend_headers.conf

```
(backend_headers) {
    header_up X-Real-IP {remote_host}
    header_up X-Forwarded-Port {args.0}
}
```

sites/webdav.conf

```
webdav.example.com:443 {
    import wildcard
    import client_headers

    reverse_proxy http://192.168.1.3:6061 {
        import backend_headers 443
    }
}
```

I don't use Caddy for certs because I need certs for IMAP, SMTP, FTPS and Samba too, my provider doesn't have a DNS API and my own script around acme-lego works (came from Apache).

On 192.168.1.3:6061 a webdav server listens:

compose:

```
services:
  sftpgo:
    container_name: webdav
    image: drakkan/sftpgo:v2-alpine-slim
    restart: always
    ports:
      - 5041:5041
      - 6061:6061
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /docker/data/sync/backup:/backup
      - /docker/data/sync/data:/var/lib/sftpgo
      - /docker/files/webdav.example.com:/files
    env_file:
      - sftpgo.env
```

sftpgo.env

```
TZ=Europe/Berlin

# Common
SFTPGO_COMMON__IDLE_TIMEOUT=15
SFTPGO_COMMON__UPLOAD_MODE=2
SFTPGO_COMMON__TEMP_PATH=/files/.temp

# Data Provider
SFTPGO_DATA_PROVIDER__USERS_BASE_DIR=/files
SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN=1

# Default
SFTPGO_DEFAULT_ADMIN_USERNAME=admin
SFTPGO_DEFAULT_ADMIN_PASSWORD=password

# HTTPD/Webinterface
SFTPGO_HTTPD__BACKUPS_PATH=/backup
SFTPGO_HTTPD__BINDINGS__0__ADDRESS=0.0.0.0
SFTPGO_HTTPD__BINDINGS__0__PORT=5041
SFTPGO_HTTPD__BINDINGS__0__HIDE_LOGIN_URL=3
SFTPGO_HTTPD__BINDINGS__0__ENABLE_WEB_CLIENT=0
SFTPGO_HTTPD__BINDINGS__0__PROXY_ALLOWED=0.0.0.0/0
SFTPGO_HTTPD__BINDINGS__0__CLIENT_IP_PROXY_HEADER="X-Forwarded-For"

# Defender
SFTPGO_COMMON__DEFENDER__ENABLED=1
SFTPGO_COMMON__DEFENDER__BAN_TIME=5
SFTPGO_COMMON__DEFENDER__BAN_TIME_INCREMENT=10
SFTPGO_COMMON__DEFENDER__THRESHOLD=5

# Log
SFTPGO_LOG_FILE_PATH=
#SFTPGO_LOG_VERBOSE=1
SFTPGO_LOG_VERBOSE=0

# --- Protocols ---

# WebDAV
SFTPGO_WEBDAVD__BINDINGS__0__PORT=6061
SFTPGO_WEBDAVD__BINDINGS__0__PROXY_ALLOWED=0.0.0.0/0
SFTPGO_WEBDAVD__BINDINGS__0__CLIENT_IP_PROXY_HEADER="X-Forwarded-For"
```
