### ISSUE TITLE
[feature request] support abstract UNIX domain socket

### ISSUE THREAD

**Issue by IceCodeNew** [caddyserver/caddy#5341]
**Use Case & Problem:**
There is a backend service that supports abstract UNIX domain sockets managed by the docker compose along with caddy. There is also a named volume for sharing the UNIX socket file between these two services.
Sometimes the backend will run into a panic and restart itself. Since there is no one cleaning the UNIX socket file before the backend restarted, the backend will fail to bind to the UNIX domain socket.

```
services:
  caddy:
    build: ./caddy/
    cap_add:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    container_name: composed-caddy
    init: true
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - share-unix-socket:/tmp/unix-socket/
      - type: bind
        source: ./caddy/
        target: /etc/caddy/
        read_only: true
  v2ray:
    cap_drop:
      - ALL
    command: [ "run", "-d", "/usr/local/etc/v2ray/conf.d/" ]
    container_name: composed-v2ray
    image: v2fly/v2fly-core:latest
    init: true
    read_only: true
    restart: always
    volumes:
      - share-unix-socket:/tmp/unix-socket/
      - type: bind
        source: ./v2ray/conf.d/
        target: /usr/local/etc/v2ray/conf.d/
        read_only: true

volumes:
  share-unix-socket:
```

```
{
	admin off
}

REPLACE_ME_V2RAY_HOSTS {
	root * /usr/share/caddy

	encode zstd gzip

	file_server

	reverse_proxy REPLACE_ME_V2RAY_PATH unix+h2c//tmp/unix-socket/send-to-v2ray.sock
}
```

---

The best solution should be to make the caddy support the abstract UNIX domain socket.
I searched for configuring a pre-hook for docker compose, to intervene in the restarting process and manually clean the UNIX domain file. But only to my disappointment to find out that this is a long stale issue and the community is unwilling to approve such a feature.
