### ISSUE TITLE
Slow config reload when using shutdown_delay

### ISSUE THREAD

**Issue by heapdavid** [caddyserver/caddy#5393]
We're currently using a `shutdown_delay` of 15 seconds to give our hardware load balancer warning of when caddy is about to go down for drains/maintenance etc as per https://caddyserver.com/docs/caddyfile/options#shutdown-delay - but this also seems to delay the config reload by the same amount. ~~During the shutdown period our load balancer marks the caddy servers offline (as it should) so we lose ingress to the swarm services until they come back online and pass the healthcheck again.~~

Should/can a reload ignore this delay?

![image](https://user-images.githubusercontent.com/88432183/221179979-5a941af9-8d72-4648-aa2f-a8454fb5dc0d.png)

**Comment by heapdavid** [comment]
Note - opened originally in https://github.com/lucaslorentz/caddy-docker-proxy as that's what we're using and the logs are from, above. Advised to open here instead.

**Comment by mholt** [comment]
Yes, the config reload and the shutdown are interrelated. What changes does your config make during the reload? If it is stopping any server/listener (i.e. the socket is not used by the new config) then it will cause the config reload to be delayed by 15s in your case.

**Comment by heapdavid** [comment]
We're seeing it during any config update done by https://github.com/lucaslorentz/caddy-docker-proxy, even when just adding a single container to the upstream IPs - wouldn't expect that to stop a server/listener, but might be down to how caddy-docker-proxy handles the reload?

I have just double-checked and it's actually showing `200 OK` (which implies `http.shutting_down=false`) from the healthcheck endpoint during the 15 seconds so looks like the issue it just limited to the time taken to load in the the new config with new upstream IPs. Disregard the bit about the load balancers - sorry!

**Comment by mholt** [comment]
I don't really know how CDP works, sorry; but in vanilla Caddy, a shutdown delay simply delays the grace period and config change for that duration first.

>I have just double-checked and it's actually showing 200 OK (which implies http.shutting_down=false) from the healthcheck endpoint during the 15 seconds so looks like the issue it just limited to the time taken to load in the the new config with new upstream IPs.

The shutdown delay should only be enforced if a server is actually closing: https://github.com/caddyserver/caddy/blob/be53e432fcac0a9b9accbc36885304639e8ca70b/modules/caddyhttp/app.go#L496-L516

What is in your logs before, during, and after a reload? (Enable debug logging first.)

**Comment by heapdavid** [comment]
I have reproduced on docker compose, with 3x whoami containers - running with this CDP generated caddyfile/json:
```
caddy-test-caddy-controller-1     | 2023-02-27T15:58:52.978559207Z{"level":"info","ts":1677513532.9780087,"logger":"docker-proxy","msg":"New Caddyfile","caddyfile":"{\n\tdebug\n\tauto_https disable_certs\n\tgrace_period 1m\n\tshutdown_delay 15s\n}\nhttp://my-test-app.com {\n\treverse_proxy 172.26.0.2:80 172.26.0.5:80 172.26.0.6:80\n}\n"}
caddy-test-caddy-controller-1     | 2023-02-27T15:58:52.978668884Z{"level":"info","ts":1677513532.9782238,"logger":"docker-proxy","msg":"New Config JSON","json":"{\"logging\":{\"logs\":{\"default\":{\"level\":\"DEBUG\"}}},\"apps\":{\"http\":{\"grace_period\":60000000000,\"shutdown_delay\":15000000000,\"servers\":{\"srv0\":{\"listen\":[\":80\"],\"routes\":[{\"match\":[{\"host\":[\"my-test-app.com\"]}],\"handle\":[{\"handler\":\"subroute\",\"routes\":[{\"handle\":[{\"handler\":\"reverse_proxy\",\"upstreams\":[{\"dial\":\"172.26.0.2:80\"},{\"dial\":\"172.26.0.5:80\"},{\"dial\":\"172.26.0.6:80\"}]}]}]}],\"terminal\":true}],\"automatic_https\":{\"disable_certificates\":true}}}}}}"}
```
I then `docker stop` one of them to make it reevaluate the caddyfile/json - note that the other two containers are still up and the change in the caddyfile is just the removal of 1 upstream IP from the reverse proxy section:
```
caddy-test-whoami-2 exited with code 2
caddy-test-whoami-2 exited with code 0
caddy-test-caddy-controller-1     | 2023-02-27T15:59:28.512347912Z{"level":"info","ts":1677513568.5118773,"logger":"docker-proxy","msg":"New Caddyfile","caddyfile":"{\n\tdebug\n\tauto_https disable_certs\n\tgrace_period 1m\n\tshutdown_delay 15s\n}\nhttp://my-test-app.com {\n\treverse_proxy 172.26.0.2:80 172.26.0.6:80\n}\n"}
caddy-test-caddy-controller-1     | 2023-02-27T15:59:28.512405919Z{"level":"info","ts":1677513568.5121088,"logger":"docker-proxy","msg":"New Config JSON","json":"{\"logging\":{\"logs\":{\"default\":{\"level\":\"DEBUG\"}}},\"apps\":{\"http\":{\"grace_period\":60000000000,\"shutdown_delay\":15000000000,\"servers\":{\"srv0\":{\"listen\":[\":80\"],\"routes\":[{\"match\":[{\"host\":[\"my-test-app.com\"]}],\"handle\":[{\"handler\":\"subroute\",\"routes\":[{\"handle\":[{\"handler\":\"reverse_proxy\",\"upstreams\":[{\"dial\":\"172.26.0.2:80\"},{\"dial\":\"172.26.0.6:80\"}]}]}]}],\"terminal\":true}],\"automatic_https\":{\"disable_certificates\":true}}}}}}"}
caddy-test-caddy-controller-1     | 2023-02-27T15:59:28.512470711Z{"level":"info","ts":1677513568.5121634,"logger":"docker-proxy","msg":"Sending configuration to","server":"172.26.0.4"}
caddy-test-caddy-server-1         | 2023-02-27T15:59:28.514301153Z{"level":"info","ts":1677513568.5135128,"logger":"admin.api","msg":"received request","method":"POST","host":"172.26.0.4:2019","uri":"/load","remote_ip":"172.26.0.3","remote_port":"57160","headers":{"Accept-Encoding":["gzip"],"Content-Length":["469"],"Content-Type":["application/json"],"User-Agent":["Go-http-client/1.1"]}}
caddy-test-caddy-server-1         | 2023-02-27T15:59:28.514837836Z{"level":"info","ts":1677513568.514546,"logger":"admin","msg":"admin endpoint started","address":"172.26.0.4:2019","enforce_origin":false,"origins":["//172.26.0.4:2019"]}caddy-test-caddy-server-1         | 2023-02-27T15:59:28.515001777Z{"level":"warn","ts":1677513568.5146751,"logger":"http","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80}
caddy-test-caddy-server-1         | 2023-02-27T15:59:28.515135325Z{"level":"info","ts":1677513568.5148222,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0004277a0"}
caddy-test-caddy-server-1         | 2023-02-27T15:59:28.515180148Z{"level":"debug","ts":1677513568.5148494,"logger":"http","msg":"starting server loop","address":"[::]:80","tls":false,"http3":false}
caddy-test-caddy-server-1         | 2023-02-27T15:59:28.515197528Z{"level":"info","ts":1677513568.5148587,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
caddy-test-caddy-server-1         | 2023-02-27T15:59:28.515222919Z{"level":"debug","ts":1677513568.5148683,"logger":"http","msg":"listener closing and shutdown delay is configured","address":":80"}
caddy-test-caddy-server-1         | 2023-02-27T15:59:28.515254733Z{"level":"debug","ts":1677513568.5148714,"logger":"http","msg":"shutdown scheduled","delay_duration":15,"time":1677513583.5148654}
caddy-test-caddy-server-1         | 2023-02-27T15:59:38.516232477Z{"level":"error","ts":1677513578.5158157,"logger":"admin","msg":"stopping current admin endpoint","error":"shutting down admin server: context deadline exceeded"}
caddy-test-caddy-server-1         | 2023-02-27T15:59:43.516006492Z{"level":"debug","ts":1677513583.5156696,"logger":"http","msg":"servers shutting down; grace period initiated","duration":60}
caddy-test-caddy-server-1         | 2023-02-27T15:59:43.516037393Z{"level":"info","ts":1677513583.515803,"logger":"tls.cache.maintenance","msg":"stopped background certificate maintenance","cache":"0xc00040b880"}
caddy-test-caddy-server-1         | 2023-02-27T15:59:43.516126124Z{"level":"info","ts":1677513583.5159376,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}
caddy-test-caddy-server-1         | 2023-02-27T15:59:43.516184078Z{"level":"info","ts":1677513583.5159612,"logger":"admin.api","msg":"load complete"}
caddy-test-caddy-controller-1     | 2023-02-27T15:59:43.516500246Z{"level":"info","ts":1677513583.5161676,"logger":"docker-proxy","msg":"Successfully configured","server":"172.26.0.4"}
```

**Comment by IndeedNotJames** [comment]
Please share the `docker-compose.yml` you used

**Comment by heapdavid** [comment]
Hi, sure - the docker-compose.yml is:
```
version: '3.8'

services:
  whoami:
    image: containous/whoami
    scale: 3
    labels:
      caddy: http://my-test-app.com
      caddy.reverse_proxy: '{{upstreams 80}}'

  caddy-server:
    image: lucaslorentz/caddy-docker-proxy
    restart: unless-stopped
    environment:
      - CADDY_DOCKER_MODE=server
      - CADDY_CONTROLLER_NETWORK=172.0.0.0/8
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
    labels:
        caddy_controlled_server:

  caddy-controller:
    image: lucaslorentz/caddy-docker-proxy
    restart: unless-stopped
    environment:
      - CADDY_DOCKER_MODE=controller
      - CADDY_DOCKER_CADDYFILE_PATH=/config/caddy/caddy_base.conf
      - CADDY_CONTROLLER_NETWORK=172.0.0.0/8
      - CADDY_DOCKER_POLLING_INTERVAL=5s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/<my username>/caddy-test/caddy_base.conf:/config/caddy/caddy_base.conf

volumes:
  caddy_data: {}
```
the caddy_base.conf is:
```
{
        debug
        auto_https disable_certs
        grace_period 1m
        shutdown_delay 15s
}
```
