### ISSUE TITLE
WebTransport support via quic-go

### ISSUE THREAD

**Issue by MonkeyBrothers** [caddyserver/caddy#5421]
hello，I have been using webtransport(base quic-go) recently to transfer some data.
I want to use caddy as my proxy forwarding, but I tried the following configuration is not feasible.

## Caddyfile:
```
{
      debug
}
webtransport.xxx.com {
      tls 2507511047@qq.com
      reverse_proxy 10.176.237.64:9001 
}
```

## docker-compse.yml:
```
version: "3.9"
services:
  caddy:
    image: caddy
    restart: unless-stopped
    network_mode: "host"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./data:/data
      - ./config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"

```
## Access error：
Failed to establish a connection to https://webtransport.xxx.com: net::ERR_METHOD_NOT_SUPPORTED

## need help
How should I configure to support the forward quic protocol？
