### ISSUE TITLE
about certificates  Auto Renew on "2096:443"

### ISSUE THREAD

**Issue by toyo2333** [caddyserver/caddy#5763]
My vps‘s https 443 requests are fallback by a frontservice to port 2096，which is bind by caddy

```
    caddy:
        image: caddy:latest
        container_name: caddy
        restart: unless-stopped
        logging:
            options:
                max-size: 10m
        ports:
            - "80:80"
            - "2096:443"
            - "2096:443/udp"
        volumes:
            - ./caddy/Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config
            -
    volumes:
        caddy_data:
            external: true
        caddy_config:
            external: true
```

my caddy  server hold a revese proxy to a container service：
here is the Caddyfile:
```
xxx.mydomain.com:2096 {
    handle {
        reverse_proxy container_name1:80
    }
    encode gzip
    log {
        format console
    }
}
```

my question is，if  i change the config to this： close port 80

        ports:
           # - "80:80" close 80 port bind
            - "2096:443"
            - "2096:443/udp"

90days later ，Will the certificates  Auto Renew Successfully？
