### ISSUE TITLE
Feature Request:  Allow Dynamic Srv Resolver address to be configured as a hostname as well as IP

### ISSUE THREAD

**Issue by gwlg-mjh** [caddyserver/caddy#5824]
Hi, 

I think I understand why you use an IP, it's for performance, you don't want to have to lookup a DNS address first before you can then lookup your SRV DNS entry.

However I am running Caddy and my DNS server as containers on the same Docker host and this is causing me a little bit of an issue, and I have what I feel is a bit of a clunky work around.

Two issues 
1) if Caddy and DNS server are on the same docker host then Caddy cannot access an externally mapped host port of another container, I believe this is called a hairpin NAT.
2) I can't use the internal container ports because I can't use Docker DNS to resolve the transient internal ip address

Workaround
I've had to create a separate bridge network that only Caddy and my DNS server use and give my DNS server a static IP on that network so I can access the internal port of the container.

I don't think the Docker DNS server would add much of a performance hit in this case.

``` yml

version: '3.7'

networks:
  internal:
    name: internal
    driver: bridge

  dynamic-caddy:
    ipam:
      driver: default
      config:
        - subnet: 10.64.32.0/24
          gateway: 10.64.32.1


services:
  dynamic-docker-caddy:
    container_name: dynamic-docker-caddy
    image: local-dns-server:latest
    restart: unless-stopped
    labels:
      - caddy.dynamic.docker.dns=caddy.example.com
      - caddy.dynamic.docker.target=dynamic-docker-caddy:5000
    volumes:
      - /opt/dynamic-docker-caddy/logs:/app/logs
      - /opt/dynamic-docker-caddy/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      dynamic-caddy:
        ipv4_address: 10.64.32.254

  caddy:
    image: caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /opt/caddy/data:/data
      - /opt/caddy/config:/config
    networks:
      - internal
      - dynamic-caddy

```

**Comment by mholt** [comment]
Thanks for opening an issue. Do you have an example of what your preferred config might look like?

**Comment by gwlg-mjh** [comment]
Thanks for looking at this, I just want to be able to use a hostname instead of an IP so e.g. `resolvers docker-dynamic-caddy:53`
If it needs to have a different option name I wouldn't mind like `resolver-hostnames docker-dynamic-caddy:53`

### However for a concrete example, if my docker environment looked like this:

```
version: '3.7'

networks:
  internal:
    name: internal
    driver: bridge

services:
  docker-dynamic-caddy:
    image: docker-dynamic-caddy:latest
    container_name: docker-dynamic-caddy
    restart: always
    labels:
      - caddy.dynamic.docker.dns=caddy.example.com
      - caddy.dynamic.docker.target=docker-dynamic-caddy:5000
    volumes:
      - /opt/docker-dynamic-caddy/logs:/app/logs
      - /opt/docker-dynamic-caddy/config:/app/config
      - /opt/docker-dynamic-caddy/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal

  caddy:
    image: caddy
    container_name: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /opt/caddy/data:/data
      - /opt/caddy/config:/config
    networks:
      - internal

  authelia:
    image: authelia/authelia
    container_name: authelia
    restart: always
    environment:
      - TZ=Europe/London
    volumes:
      - /opt/authelia:/config
    networks:
      - internal
```


### Then my caddy config would look like this.

```
{
    log {
        output stdout
    }
        on_demand_tls {
        ask http://docker-dynamic-caddy:5000/ask
    }
}

(auth) {
    forward_auth authelia:9091 {
        uri /api/verify?rd=https://auth.example.com/
        copy_headers Remote-User Remote-Groups Remote-Name Remote-Email
    }
}

https://auth.example.com {
    reverse_proxy http://authelia:9091
}

*.example.com {
    import auth
    reverse_proxy {
        dynamic srv "srv-{http.request.host}" {
            resolvers docker-dynamic-caddy:53
        }
    }
    tls {
        on_demand
    }
}
```
