### ISSUE TITLE
[Feature] Add the ability to validate imported configuration unitary

### ISSUE THREAD

**Issue by M0NsTeRRR** [caddyserver/caddy#5958]
When deploying config through ansible, you can't validate template configuration with `validate` command from caddy.
`validate` param in `ansible.builtin.template` is a command to run before copying the updated file into the final destination.
A temporary file path is used to validate, passed in through ‘%s’ which must be present.

Currently you can't validate imported configuration in a unitary manner. The idea behind that is to test configuration before putting it in the production folder. I could validate configuration in the final location directly but I will lost the old configuration (that is working, to rollback if needed) and it will prevent any restart/reload of Caddy until the file is fixed.

Error log : 
```
2023/11/28 21:09:54.960 INFO    using provided configuration    {"config_file": "conf.d/test.fr.conf", "config_adapter": "caddyfile"}
Error: adapting config using caddyfile: File to import not found: webconf, at conf.d/test.fr.conf:6
```

A minimal configuration example :
`/etc/caddy/Caddyfile`
```
{
    email admin@test.fr
}

# Add gzip compression to requests
(webconf) {
  encode gzip
}

import /etc/caddy/conf.d/*.conf
```

`/etc/caddy/conf.d/test.fr.conf` :
```
test.fr {
    reverse_proxy http://localhost:3000 {
            header_up Set-Cookie "test.fr"
    }

    import webconf
}
```

Ansible tasks example :
```
- name: Configure default Caddy config
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile

- name: Configure Caddy
  ansible.builtin.template:
    src: site.conf.j2
    dest: /etc/caddy/conf.d/test.fr.conf
    validate: /usr/bin/caddy validate --config %s --adapter caddyfile
```
