### ISSUE TITLE
caddy doesn't seem to support http1.1 upgrade to h2c when being reverse proxied by traefik

### ISSUE THREAD

**Issue by unknowndevQwQ** [caddyserver/caddy#5992]
I use traefik as a gateway to handle tls, and then try to forward some of the requests to caddy via h2c. however, when accessing the site, traefik returns an internal server error. after looking at the traefik logs, I see that caddy is experiencing h2c-related problems when traefik forwards the requests to caddy problem.

When I searched for a PRI for HTTP2 I found the following:
[PRI method in http2 implementation causing issue](https://stackoverflow.com/questions/50434269/pri-method-in-http2-implementation-causing-issue)
[This method is never used by an actual client. This method will appear to be used when an HTTP/1.1 server or intermediary attempts to parse an HTTP/2 connection preface.](https://datatracker.ietf.org/doc/html/rfc7540#section-3.5)

Maybe logs and configuration files are not necessary, but I'm providing them anyway to avoid surprises.

caddy log snippets: `2023/12/18 08:06:46.958 ERROR   http.log.access.local-loop      handled request :`
```
{
    "request": {
        "remote_ip": "127.0.0.1", 
        "remote_port": "45494", 
        "client_ip": "127.0.0.1", 
        "proto": "HTTP/2.0", 
        "method": "PRI", 
        "host": "", 
        "uri": "*", 
        "headers": { }
    }, 
    "bytes_read": 0, 
    "user_id": "", 
    "duration": 0.000096402, 
    "size": 0, 
    "status": 404, 
    "resp_headers": {
        "Server": [
            "Caddy"
        ]
    }
}

```
traefik log snippets: 

```
{
    "ClientAddr": "$ip:$port", 
    "ClientHost": "$ip", 
    "ClientPort": "50060", 
    "ClientUsername": "-", 
    "DownstreamContentSize": 21, 
    "DownstreamStatus": 500, 
    "Duration": 6293903, 
    "OriginContentSize": 21, 
    "OriginDuration": 6164759, 
    "OriginStatus": 500, 
    "Overhead": 129144, 
    "RequestAddr": "$domain", 
    "RequestContentSize": 0, 
    "RequestCount": 5446, 
    "RequestHost": "$domain", 
    "RequestMethod": "GET", 
    "RequestPath": "/1", 
    "RequestPort": "-", 
    "RequestProtocol": "HTTP/2.0", 
    "RequestScheme": "https", 
    "RetryAttempts": 0, 
    "RouterName": "https@file", 
    "ServiceAddr": "127.0.0.1:8080", 
    "ServiceName": "http@file", 
    "ServiceURL": {
        "Scheme": "h2c", 
        "Opaque": "", 
        "User": null, 
        "Host": "127.0.0.1:8080", 
        "Path": "", 
        "RawPath": "", 
        "OmitHost": false, 
        "ForceQuery": false, 
        "RawQuery": "", 
        "Fragment": "", 
        "RawFragment": ""
    }, 
    "StartLocal": "2023-12-18T...", 
    "StartUTC": "2023-12-18T...", 
    "TLSCipher": "TLS_AES_128_GCM_SHA256", 
    "TLSVersion": "1.3", 
    "entryPointName": "https", 
    "level": "info", 
    "msg": "", 
    "request_Accept": "*/*", 
    "request_User-Agent": "curl/8.5.0", 
    "request_X-Forwarded-Host": "$domain", 
    "request_X-Forwarded-Port": "443", 
    "request_X-Forwarded-Proto": "https", 
    "request_X-Forwarded-Server": "$linux_machine_name", 
    "request_X-Real-Ip": "$ip", 
    "time": "2023-12-18T..."
}
```

caddy config file:

```
{
        admin "unix//run/caddy/admin.socket"
        auto_https disable_certs
        servers :8080 {
                protocols h2c h1
        }
}

:8080 {
        bind "127.0.0.1"
        log local-loop {
                format console
                output file /var/log/caddy/access-local.log
        }

        root * /srv/http
        file_server

}
```

traefik config file:

`dynamic.yml`

```
http:
  routers:
    https:
      entryPoints:
        - "https"
      rule: "Host(`$domain`, `$domain2`) || HostRegexp(`{subdomain:[a-z\\.]+}.$domain`)"
      service: http
      tls: {}

    http-acme:
      entryPoints:
        - "http"
      rule: "HostRegexp(`{catch_all:.*}`) && PathPrefix(`/.well-known/acme-challenge`)"
      service: http
      priority: 999

  services:
    http:
      loadBalancer:
        servers:
          - url: "h2c://127.0.0.1:8080"
```

`static.yml`

```
[entryPoints]
  [entryPoints.http]
    address = ":80"

  [entryPoints.https]
    address = ":443"

[log]
level = "INFO"

[accessLog]
  format = "json"
  [accessLog.fields]
    defaultMode = "keep"
    [accessLog.fields.headers]
      defaultMode = "keep"

[providers.file]
directory = "/etc/traefik/conf.d"
watch = true
```
