### ISSUE TITLE
caddy reload always points to the default file name

### ISSUE THREAD

**Issue by linxic4** [caddyserver/caddy#6039]
cat compose.yaml
```
version: '3.9'
services:
  caddy:
    container_name: caddy
    image: caddy:latest
    restart: always
    tty: true
    networks:
      current:
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2019/metrics"]
      start_period: 60s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - /data/caddy/html:/srv
      - /data/caddy/data:/data/caddy
      - /data/caddy/config:/etc/caddy/config
    environment:
      - TZ=Asia/Shanghai
      - UMASK=022
      - PUID=0
      - PGID=0
    cap_add:
      - NET_ADMIN
    command:
        caddy run --config /etc/caddy/config --adapter caddyfile
networks:
  current:
    name: current
    driver: bridge
```
According to the normal caddy reload method, it should be "docker exec -w /etc/caddy caddy caddy reload".
But I changed the default Caddyfile and executing "caddy reload" would point to a non-existent configuration file, causing the server to stop running.
He didn't read the configuration file (config) that my caddy ran, but read the default file name in the folder, which I think is an unreasonable place.

>INFO    http    servers shutting down with eternal grace period
>INFO    autosaved config (load with --resume flag)      {"file": "/config/caddy/autosave.json"}
>INFO    admin.api       load complete
>INFO    admin   stopped previous server {"address": "localhost:2019"}
