### ISSUE TITLE
Encountered "Address already in use" error after updating to the latest Caddy Docker image

### ISSUE THREAD

**Issue by toyo2333** [caddyserver/caddy#6067]
Today, I encountered an issue after pulling a new version of Caddy when using docker-compose pull and docker-compose up -d.

The error message received was response from daemon: Address already in use.

Upon inspecting the network, I discovered that the IP address 172.19.0.5 had been assigned to containerb.

This situation has never occurred before.

As a solution, I reverted the Caddy image version back to the previous one, which is 2.7.5.

After making this change, everything is working fine.

Is this a bug in the latest Caddy Docker image?

Here is a example of my config
```
    caddy:
        image: caddy:latest
        # image: caddy:2.7.5
        networks:
            my_network:
                ipv4_address: 172.19.0.5
                container_name: caddy
                restart: unless-stopped

    containerb:
        image: containerb:xxxx
        networks:
            - my_network
        container_name: containerb
        restart: always

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16 
```
