### ISSUE TITLE
Metrics of HTTPS servers do not seem to work reliably

### ISSUE THREAD

**Issue by ungive** [caddyserver/caddy#6455]
I have created a minimum working example that reproduces an issue I am having with Caddy metrics. I was surprised to see that metrics for all my configured servers were working when I tested my application locally (without HTTPS, only HTTP ports and without any domain names), but it didn't anymore when I switched to using my domain.

I have tried different things, like additionally enabling the metrics globally (`{ servers { metrics} }`), renaming the servers to something else, using the builder image to use the latest version of caddy (see `caddy.dockerfile` below) and trying to move the metrics endpoint to an HTTPS domain as well, even though that makes the data public, just to see if it works. Nothing helped and I am a bit frustrated about how to get metrics working with HTTPS.

Consider the following docker-compose.yml and two Caddyfiles:
```yml
services:
  caddy-working:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080" # metrics
    volumes:
      - ./working.caddyfile:/etc/caddy/Caddyfile
      - caddy_data_working:/data
      - caddy_config_working:/config
  caddy-notworking:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "443:443"
      - "443:443/udp"
      - "8080:8080" # metrics
    volumes:
      - ./notworking.caddyfile:/etc/caddy/Caddyfile
      - caddy_data_notworking:/data
      - caddy_config_notworking:/config

volumes:
  caddy_data_working:
  caddy_config_working:
  caddy_data_notworking:
  caddy_config_notworking:
```
```
# working.caddyfile
{
	servers :8080 {
		name metrics
		metrics
	}

	servers :80 {
		name proxy
		metrics
	}
}

:8080 {
	metrics /metrics
}

:80 {
	respond "proxy"
}
```
```
# notworking.caddyfile
{
	servers :8080 {
		name metrics
		metrics
	}

	servers proxy.example.com {
		name proxy
		metrics
	}
}

:8080 {
	metrics /metrics
}

proxy.example.com {
	respond "proxy"
}
```
`proxy.example.com` is a placeholder for my own domain, which simply points to my server (with A and AAAA records).

Try the working example:
```
$ sudo docker compose up -d caddy-working
$ curl -s http://localhost:8080/metrics | grep -o "server=\"\w*\"" | sort | uniq
server="metrics"
$ curl http://localhost:80
proxy
$ curl -s http://localhost:8080/metrics | grep -o "server=\"\w*\"" | sort | uniq
server="metrics"
server="proxy"
```
As you can see, once I requested the "proxy" server, there are metrics for it available at the `:8080/metrics` endpoint.

Now try the example that does not work:
```
$ sudo docker compose down -v
$ sudo docker compose up -d caddy-notworking
$ curl -s http://localhost:8080/metrics | grep -o "server=\"\w*\"" | sort | uniq
server="metrics"
$ curl https://proxy.example.com
proxy
$ curl -s http://localhost:8080/metrics | grep -o "server=\"\w*\"" | sort | uniq
server="metrics"
```
With this example the only metrics that are ever available are for the metrics endpoint itself, never for the "proxy" server.

The only workaround I can think of right now is to publish metrics on every server, secure them with a password and then scrape them from each server instead of from the single endpoint I have in the examples above. Maybe I'm missing something here, but I don't know how to proceed and if this is intended behaviour.

I'm thankful for any help!

Appendix: `caddy.dockerfile` that I used instead of `docker:latest`. Used this initially instead of `caddy:latest` because I needed the cache handler.
```dockerfile
FROM caddy:builder AS builder

RUN xcaddy build \
    --with github.com/caddyserver/cache-handler

FROM caddy:latest

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```
