### ISSUE TITLE
no certificate available for <docker container ip>

### ISSUE THREAD

**Issue by bykof** [caddyserver/caddy#6482]
Hi dear caddy Team, 
I got a problem today that I am not able to fix by myself.

Somehow I get the error: 
```
caddy-1  | {"level":"debug","ts":1722078527.5707881,"logger":"http.stdlib","msg":"http: TLS handshake error from 167.235.203.100:35474: no certificate available for '172.19.0.2'"}
```

`172.19.0.2` is the docker container's IP but I setup a proper IP in my Caddyfile which is the `<public ip>`.

Did I misused caddy here? How can I tell it, just to use self-signed certs and to use my public ip?

`docker-compose.yml`:

```
services:
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "9080:9080"
      - "9081:9081"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
...
```

`Caddyfile`:

```
<public ip>:9080 {
    reverse_proxy cadvisor:8080
    tls internal
    basic_auth {
        a b
    }
}

<public ip>:9081 {
    reverse_proxy node_exporter:9100
    tls internal
    basic_auth {
        a b 
    }
}
```
