### ISSUE TITLE
reverseproxy.statusError (reverseproxy.go:1269)

### ISSUE THREAD

**Issue by cruvie** [caddyserver/caddy#6605]
encountered an error today, works fine before, can anyone tell me what cause the problem
```sh
2024-10-04 15:42:56 {"level":"error","ts":1728027776.6026268,"logger":"http.log.error","msg":"EOF","request":{"remote_ip":"192.168.xx.1","remote_port":"55796","client_ip":"192.168.xx.1","proto":"HTTP/1.1","method":"POST","host":"xxx.75.xx.116:9080","uri":"/moment/getMomentList","headers":{"Content-Length":["4"],"Authorizationtoken":["eyJhbGciOiJIUzI1IlVzZXJJZCI6MTYzNzcyMzY2MTU3MTk4NTQwOCwiVXNlcm5hbWUiOiIiLCJQbGF0Zm9ybSI6Mn0sImlzcyI6ImNydXZpZSIsImV4cCI6MTczMTcwNjM5MCwibmJmIjoxNzI2NTIyMzkwLCJpYXQiOjE3MjY1MjIzOTB9.yTQN_lMPUS8h3PcJDoOC3kgPpPJ64-ObqrSgYHB_r6Q"],"User-Agent":["Dart/3.5 (dart:io)"],"Content-Type":["application/protobuf"],"Accept-Encoding":["gzip"]}},"duration":0.009962583,"status":502,"err_id":"37822zh1t","err_trace":"reverseproxy.statusError (reverseproxy.go:1269)"}
```
docker-compose
```yml
  ss-caddy:
    image: caddy:latest
    container_name: ss-caddy
    restart: unless-stopped
    ports:
      - "9080:9080"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/caddy_data:/data
      - ./caddy/caddy_config:/config
```
caddyfile
```
:9080 {
	reverse_proxy /xx/* host.docker.internal:8757
    reverse_proxy /mxxx/* host.docker.internal:8758
    reverse_proxy /daxx/* host.docker.internal:8759
    reverse_proxy /tool/* host.docker.internal:8755
    reverse_proxy /uxxx/* host.docker.internal:8756
    reverse_proxy /msxxx/* host.docker.internal:8754
}
```
version
```sh
/srv # caddy -v
v2.8.4 h1:q3pe0wpBj1OcHFZ3n/1nl4V4bxBrYoSoab7rL9BMYNk=
```
