### ISSUE TITLE
readdirent xxx: invalid argument

### ISSUE THREAD

**Issue by hongbo-miao** [caddyserver/caddy#6831]
I am trying to use [mountpont-s3](https://github.com/awslabs/mountpoint-s3) to mount S3 folder to a Kubernetes pod, and then use Caddy `browse` as a server to serve the folder to the client.

I deployed it to an existing Kubernetes cluster which uses Traefik as Ingress.

Here is my deployment code:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hm-s3-browser-deployment
  namespace: production-hm-s3-browser
  labels:
    app.kubernetes.io/name: hm-s3-browser-deployment
    app.kubernetes.io/part-of: production-hm-s3-browser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hm-s3-browser
  template:
    metadata:
      labels:
        app: hm-s3-browser
    spec:
      containers:
        - name: s3-browser
          image: public.ecr.aws/docker/library/caddy:2.9.1-alpine
          ports:
            - name: s3-browser
              protocol: TCP
              containerPort: 8080
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "{
                debug
                auto_https off
              }
              :8080 {
                encode zstd gzip
                root * /srv
                file_server browse
              }" > /etc/caddy/Caddyfile
              caddy run --config /etc/caddy/Caddyfile
          volumeMounts:
            - name: parquet-my-data-volume
              mountPath: /srv/my_data
      volumes:
        - name: parquet-my-data-volume
          persistentVolumeClaim:
            claimName: parquet-my-data-persistent-volume-claim
```
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: hm-s3-browser-service
  namespace: production-hm-s3-browser
  labels:
    app.kubernetes.io/name: hm-s3-browser-service
    app.kubernetes.io/part-of: production-hm-s3-browser
spec:
  type: ClusterIP
  selector:
    app: hm-s3-browser
  ports:
    - name: s3-browser
      protocol: TCP
      targetPort: s3-browser
      port: 8080
```
```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hm-s3-browser-ingress
  namespace: production-hm-s3-browser
  annotations:
    kubernetes.io/ingress.class: traefik
    # https://doc.traefik.io/traefik/routing/providers/kubernetes-ingress/#on-ingress
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    # https://kubernetes-sigs.github.io/external-dns/latest/annotations/annotations
    external-dns.alpha.kubernetes.io/hostname: hm-s3-browser.example.com
    # https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks
    argocd.argoproj.io/hook: PostSync
  labels:
    app.kubernetes.io/name: hm-s3-browser-ingress
    app.kubernetes.io/part-of: production-hm-s3-browser
spec:
  rules:
    - host: hm-s3-browser.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hm-s3-browser-service
                port:
                  number: 8080
  tls:
    - hosts:
        - hm-s3-browser.example.com
      secretName: production-hm-s3-browser-certificate
```
```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parquet-my-data-persistent-volume-claim
  namespace: production-hm-s3-browser
  annotations:
    # https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks
    argocd.argoproj.io/hook: PreSync
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: parquet-my-data-persistent-volume
```
```yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: parquet-my-data-persistent-volume
  namespace: production-hm-s3-browser
  annotations:
    # https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks
    argocd.argoproj.io/hook: PreSync
spec:
  capacity:
    storage: 1Gi # This value is required but ignored by the CSI driver
  accessModes:
    - ReadOnlyMany
  mountOptions:
    # https://github.com/awslabs/mountpoint-s3/blob/main/doc/CONFIGURATION.md
    - region=us-west-2
    - prefix=data/raw-parquet/my_data/
    - metadata-ttl=300 # seconds
  csi:
    driver: s3.csi.aws.com
    volumeHandle: parquet-my-data-volume-handle
    volumeAttributes:
      bucketName: my-bucket
```

When I go https://hm-s3-browser.example.com, I can see `my_data` folder. And it always succeed opening.
However, when I try to open https://hm-s3-browser.example.com/my_data , sometimes it succeed, sometimes it failed. When it failed, the Caddy pod shows error

> {"level":"error","ts":1739091513.4532545,"logger":"http.log.error","msg":"readdirent /srv/my_data: invalid argument","request":{"remote_ip":"172.31.167.217","remote_port":"33902","client_ip":"172.31.167.217","proto":"HTTP/1.1","method":"GET","host":"hm-s3-browser.example.com","uri":"/my_data/","headers":{"Accept-Encoding":["gzip, deflate, br, zstd"],"Accept-Language":["en-US,en;q=0.8"],"Sec-Ch-Ua":["\"Not A(Brand\";v=\"8\", \"Chromium\";v=\"132\", \"Brave\";v=\"132\""],"Pragma":["no-cache"],"Sec-Fetch-Site":["none"],"X-Forwarded-Proto":["https"],"Sec-Fetch-Dest":["document"],"Upgrade-Insecure-Requests":["1"],"X-Real-Ip":["172.31.191.116"],"Cache-Control":["no-cache"],"Sec-Ch-Ua-Mobile":["?0"],"X-Forwarded-Server":["hm-traefik-546958b885-hlt9g"],"Sec-Gpc":["1"],"X-Forwarded-Host":["hm-s3-browser.example.com"],"Sec-Fetch-Mode":["navigate"],"Sec-Fetch-User":["?1"],"X-Forwarded-Port":["443"],"Priority":["u=0, i"],"X-Forwarded-For":["172.31.191.116"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36"],"Sec-Ch-Ua-Platform":["\"macOS\""],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8"]}},"duration":0.105661807,"status":500,"err_id":"bsmvi1n4d","err_trace":"fileserver.(*FileServer).serveBrowse (browse.go:126)"}

If I ssh into this pod, I can always succeed listing `/srv/my_data` folder.

Any suggestions would be appreciate. Thanks! ☺️
