### ISSUE TITLE
Docker Caddy:2 trusted_proxies not recognized

### ISSUE THREAD

**Issue by Neonsy** [caddyserver/caddy#7041]
# Setup

I have a front facing caddy container that is exposed like that:

```yml
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - data:/data
      - config:/config
      - caddyfiles:/etc/caddy
```

On a certain domain it directs as reverse proxy to another caddy that is also **`caddy:2`** and that one does the same to a fpm container.

Therefore the caddy of the **`PHP-FMP`** stack is in both the **`public_proxy`** and it's **`default`** stack networks.

## Problem

However, based on research I need the **`trusted_proxies`** directive so that the **`PHP-FPM`** app can trust what the front facing caddy sends down.

### Access flow

:80,443 via domain block: Front Facing Caddy (FFC) -> :80 Stack Caddy (SC) -> PHP

SC gets the X PROTO header with the value https, but the PHP container when dumping $_SERVER says it's http, and my search has told me that PHP does not know to trust the FFC value.

## Attempted solution

To solve it I need to use the trusted_proxies directive, but it's not being found. I've even tried making my own caddy image but still it's not there, even when checking via **`caddy list-modules`**
