### ISSUE TITLE
Spurious "DNS challenge enabled, but no DNS provider configured" since 2.10.0

### ISSUE THREAD

**Issue by legeana** [caddyserver/caddy#7097]
Hi, since caddy 2.10 I am getting a spurious `provision tls.issuance.acme: DNS challenge enabled, but no DNS provider configured` error. The minimum Caddyfile is below. Caddy 2.9 doesn't have the same issue.

I am very confused why this is happening. I don't have the DNS challenge configured at all, I am using tlsalpn challenge instead.

Caddyfile:

```
{
    email root@liri.ie
    log default {
        format console
    }
    ocsp_stapling off
}
www.liri.ie {
    reverse_proxy 172.19.0.10:3000 {
        trusted_proxies 172.19.0.0/16
    }
    header Strict-Transport-Security max-age=63072000;includeSubDomains;preload
    tls {
        issuer acme {
            disable_http_challenge
            propagation_timeout 10m
            propagation_delay 2m
        }
    }
}
```

Full error: `caddy-1  | 2025-06-28T19:20:06.941099427Z Error: loading initial config: loading new config: loading http app module: provision http: getting tls app: loading tls app module: provision tls: provisioning automation policy 0: loading TLS automation management module: position 0: loading module 'acme': provision tls.issuance.acme: DNS challenge enabled, but no DNS provider configured`.

docker-compose.yaml

```
    caddy:
      image: caddy:2.10
      restart: unless-stopped
      cap_add:
        - NET_ADMIN
      ports:
        - 2080:80
        - 443:443
        - 443:443/udp
      environment:
        TZ: 'Europe/Dublin'
        PUID: '99'
        PGID: '100'
      labels:
        net.unraid.docker.icon: https://d1q6f0aelx0por.cloudfront.net/product-logos/library-caddy-logo.png
      networks:
        - docker-proxy
        - docker-services
      volumes:
        - /mnt/user/appdata/CaddyV2/Caddyfile.manual:/etc/caddy/Caddyfile
        # this volume is needed to keep the certificates
        # otherwise, new ones will be re-issued upon restart
        - /mnt/user/appdata/CaddyV2/data:/data
```
